# Generated by Django 2.0.1 on 2018-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
